apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: php-port
      protocol: TCP
      port: 5000
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 172.17.0.4
